public enum ItrKindEnum {
    CHAR_NORMAL_HIT = 0,
    CHAR_CATCH = 1,
    CHAR_ALLY = 2,
    CHAR_OWNER = 3,
    CHAR_EMPLOYEES = 4,
    CHAR_SELF = 5,

    EFFECT_NORMAL_HIT = 10,
    EFFECT_CATCH = 11,
    EFFECT_ALLY = 12,
    EFFECT_OWNER = 13,
    EFFECT_EMPLOYEES = 14,
    EFFECT_SELF = 15,

    POWER_NORMAL_HIT = 20,
    POWER_CATCH = 21,
    POWER_ALLY = 22,
    POWER_OWNER = 23,
    POWER_EMPLOYEES = 24,
    POWER_SELF = 25,

    ALL = 8,
}
